name: coolweather
description: A new Flutter application about weather forecast.

version: 1.0.3+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: '>=0.11.3+12'
  quiver: '>=2.0.0 <3.0.0'
  json_annotation: ^2.0.0
  shared_preferences: ^0.5.3+4
  amap_location:
  fluttertoast: ^3.1.3
  permission_handler: ^3.2.0
  provider: ^3.1.0
  package_info: ^0.4.0+6

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/sunny.jpg
    - images/location_ic.png
    - images/main_bg_2.png
    - images/building_ic.png
    - images/ic_launcher.png
    - images/weather/cloud_ic.png
    - images/weather/haze_ic.png
    - images/weather/nosun_ic.png
    - images/weather/rain_ic.png
    - images/weather/snow_ic.png
    - images/weather/sunny_ic.png
    - images/weather/wind_ic.png

  fonts:
    - family: Oxygen-Regular
      fonts:
        - asset: assets/fonts/Oxygen-Regular.ttf
    - family: Oxygen-Light
      fonts:
        - asset: assets/fonts/Oxygen-Light.ttf